# Generated by Django 2.1.3 on 2018-11-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAnalysis',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('instrument', models.CharField(max_length=5)),
                ('market', models.CharField(max_length=5)),
                ('year', models.IntegerField()),
                ('polarity', models.FloatField()),
            ],
        ),
    ]
