# Generated by Django 2.1.3 on 2018-11-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_extractor', '0002_auto_20181126_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportanalysis',
            old_name='instrumentid',
            new_name='instrument',
        ),
        migrations.AlterField(
            model_name='instrument',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reportanalysis',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
