# Generated by Django 2.1.3 on 2019-02-17 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_extractor', '0003_auto_20181126_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('date', models.TimeField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='info_extractor.Instrument')),
            ],
        ),
    ]
