# Generated by Django 2.1.3 on 2019-03-01 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_extractor', '0006_historicprices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dps', models.FloatField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='info_extractor.Instrument')),
            ],
        ),
    ]
