# Generated by Django 2.1.3 on 2019-03-27 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_extractor', '0007_dividend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(max_length=128)),
                ('value', models.FloatField()),
                ('date', models.DateField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='info_extractor.Market')),
            ],
        ),
        migrations.AlterField(
            model_name='instrument',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='info_extractor.Market'),
        ),
    ]
