# Generated by Django 2.1.3 on 2019-03-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_extractor', '0008_auto_20190327_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketdata',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='measure',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
